import { useEffect, useMemo, useState } from 'react';
import { AppState, PatientCase, TaskThread } from './types';
import { defaultState, loadState, saveState } from './utils/storage';
import HeaderSummary from './components/HeaderSummary';import BottomNav from './components/BottomNav';import FieldNotes from './components/FieldNotes';import TaskComposer from './components/TaskComposer';import PatientCaseCard from './components/PatientCaseCard';import SwagSelector from './components/SwagSelector';import { dueCount, isDue, nowIso } from './utils/reminders';import { sortCases } from './utils/sorting';import { fireDueAlert, requestAlerts } from './utils/notifications';
const id=()=>crypto.randomUUID?.()??`${Date.now()}-${Math.random()}`;
export default function App(){const [state,setState]=useState<AppState>(defaultState);const [tab,setTab]=useState<'board'|'add'|'notes'>('board');const [room,setRoom]=useState('');const [swag,setSwag]=useState<1|2|3|4|5>(3);const [taskText,setTaskText]=useState('');const [reminder,setReminder]=useState(0);const [caseForTask,setCaseForTask]=useState<string>('');const [toast,setToast]=useState('');
useEffect(()=>setState(loadState()),[]);useEffect(()=>saveState(state),[state]);
const activeCases=state.patientCases.filter(c=>!c.isCleared);const activeTasks=state.taskThreads.filter(t=>!t.isCompleted);const dueTasks=activeTasks.filter(t=>isDue(t));
useEffect(()=>{const check=()=>{const unalerted=state.taskThreads.filter(t=>isDue(t)&&!t.lastAlertedAt);if(unalerted.length){fireDueAlert(unalerted);setState(s=>({...s,taskThreads:s.taskThreads.map(t=>unalerted.find(u=>u.id===t.id)?{...t,lastAlertedAt:nowIso()}:t)}));}};check();const iv=setInterval(check,20000);window.addEventListener('focus',check);document.addEventListener('visibilitychange',check);return()=>{clearInterval(iv);window.removeEventListener('focus',check);document.removeEventListener('visibilitychange',check);};},[state.taskThreads]);
const addTask=(caseId:string|null,text:string,mins:number)=>{const dueAt=mins?new Date(Date.now()+mins*60000).toISOString():null;setState(s=>({...s,taskThreads:[{id:id(),caseId,text,createdAt:nowIso(),isCompleted:false,reminderMinutes:mins||null,dueAt,lastAlertedAt:null,snoozeCount:0},...s.taskThreads]}));};
const sorted=useMemo(()=>sortCases(activeCases,state.taskThreads),[activeCases,state.taskThreads]);
return <main className='max-w-md mx-auto p-3 pb-24 space-y-3'>{tab==='board'&&<><HeaderSummary seen={state.patientSeenCount} target={state.patientTarget} setSeen={(n)=>setState(s=>({...s,patientSeenCount:n}))} openCases={activeCases.length} openThreads={activeTasks.length} dueNow={dueTasks.length}/><div className='card text-xs'>Alerts when supported by your device/browser. <button className='border ml-2' onClick={()=>requestAlerts()}>Enable alerts</button></div>{dueTasks.length>0&&<div className='card bg-amber-50 border-amber-300'><b>{dueTasks.length} threads are back in mind</b></div>}{sorted.map(pc=><PatientCaseCard key={pc.id} pc={pc} tasks={state.taskThreads.filter(t=>t.caseId===pc.id)} onSwag={(v)=>setState(s=>({...s,patientCases:s.patientCases.map(c=>c.id===pc.id?{...c,acuitySwag:v,updatedAt:nowIso()}:c)}))} onAddTask={()=>{setTab('add');setCaseForTask(pc.id);}} onToggleTask={(tid)=>{setState(s=>({...s,taskThreads:s.taskThreads.map(t=>t.id===tid?{...t,isCompleted:true,completedAt:nowIso()}:t)}));setToast('Thread completed. Undo?')}} onSnooze={(tid,m)=>setState(s=>({...s,taskThreads:s.taskThreads.map(t=>t.id===tid?{...t,dueAt:new Date(Date.now()+m*60000).toISOString(),lastAlertedAt:null,snoozeCount:(t.snoozeCount||0)+1}:t)}))} onClear={()=>{const open=state.taskThreads.filter(t=>t.caseId===pc.id&&!t.isCompleted).length;if(open&& !window.confirm(`Room ${pc.room} still has ${open} open threads. Clear anyway?`))return;setState(s=>({...s,patientCases:s.patientCases.map(c=>c.id===pc.id?{...c,isCleared:true,clearedAt:nowIso()}:c),recentlyClearedCaseIds:[pc.id,...s.recentlyClearedCaseIds].slice(0,10)}));setToast(`Room ${pc.room} cleared. Undo?`);}}/>)}<div className='card'><details><summary>Recently cleared</summary>{state.recentlyClearedCaseIds.map(id=>{const pc=state.patientCases.find(c=>c.id===id);if(!pc)return null;return <div key={id} className='flex justify-between py-1'><span>Room {pc.room}</span><button className='border' onClick={()=>setState(s=>({...s,patientCases:s.patientCases.map(c=>c.id===id?{...c,isCleared:false,clearedAt:null}:c)}))}>Restore</button></div>})}</details></div>{toast&&<div className='fixed top-2 left-2 right-2 bg-slate-900 text-white p-2 rounded-xl'>{toast}</div>}</>}
{tab==='add'&&<div className='space-y-3'><div className='card space-y-2'><h2 className='font-semibold'>New Patient Case</h2><input className='w-full border rounded-xl p-2' placeholder='Room number or non-identifying cue' value={room} onChange={e=>setRoom(e.target.value)}/><p className='text-xs'>Room/cue only. Avoid patient-identifying details.</p><SwagSelector value={swag} onChange={setSwag}/><TaskComposer text={taskText} setText={setTaskText} reminder={reminder} setReminder={setReminder} onSave={()=>{if(room.trim()){const cid=id();const created=nowIso();setState(s=>({...s,patientCases:[{id:cid,room:room.trim(),acuitySwag:swag,createdAt:created,updatedAt:created,isCleared:false,clearedAt:null},...s.patientCases]}));if(taskText.trim())addTask(cid,taskText,reminder);setRoom('');setTaskText('');setReminder(0);setTab('board');}}}/></div><div className='card space-y-2'><h2 className='font-semibold'>Add Task to Existing Case</h2><select className='w-full border rounded-xl p-2' value={caseForTask} onChange={e=>setCaseForTask(e.target.value)}><option value=''>Select room</option>{activeCases.map(c=><option key={c.id} value={c.id}>Room {c.room}</option>)}</select><TaskComposer text={taskText} setText={setTaskText} reminder={reminder} setReminder={setReminder} onSave={()=>{if(taskText.trim()){addTask(caseForTask||null,taskText,reminder);setTaskText('');setReminder(0);setTab('board');}}}/></div></div>}
{tab==='notes'&&<FieldNotes notes={[...state.fieldNotes].sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime())} onSave={(text,tag)=>setState(s=>({...s,fieldNotes:[{id:id(),text,tag,createdAt:nowIso()},...s.fieldNotes]}))} onDelete={(nid)=>setState(s=>({...s,fieldNotes:s.fieldNotes.filter(n=>n.id!==nid)}))}/>}<BottomNav tab={tab} setTab={setTab}/></main>}
